=== oddbookworm/PiBoy/configs/Perks.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="perks" type="perksType"/>
  <xs:complexType name="perksType">
    <xs:sequence>
      <xs:element name="perk" type="perkType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="perkType">
    <xs:sequence>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="requirements" type="requirementsType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="requirementsType">
    <xs:sequence>
      <xs:element name="intelligence" type="xs:unsignedInt" minOccurs="0"/>
      <xs:element name="level" type="xs:unsignedInt" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== oddbookworm/PiBoy/configs/Perks.xml
<?xml version="1.0" encoding="UTF-8"?>
<perks xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./Perks.xsd">
  <perk name="Gun Nut 1">
    <description>
    You can modify small guns and heavy weapons with weapon mods.
    Unlocks rank 1 mods.
    </description>
    <requirements>
      <intelligence>6</intelligence>
      <level>2</level>
    </requirements>
  </perk>
  <perk name="Gun Nut 2">
    <description>
    You can modify small guns and heavy weapons with weapon mods.
    Unlocks rank 2 mods.
    </description>
    <requirements>
      <intelligence>6</intelligence>
      <level>6</level>
    </requirements>
  </perk>
  <perk name="Gun Nut 3">
    <description>
    You can modify small guns and heavy weapons with weapon mods.
    Unlocks rank 3 mods.
    </description>
    <requirements>
      <intelligence>6</intelligence>
      <level>10</level>
    </requirements>
  </perk>
  <perk name="Gun Nut 4">
    <description>
    You can modify small guns and heavy weapons with weapon mods.
    Unlocks rank 4 mods.
    </description>
    <requirements>
      <intelligence>6</intelligence>
      <level>14</level>
    </requirements>
  </perk>
</perks>
